### ISSUE TITLE
assignment 6 : update_gate does not need to do sigmoid

### ISSUE THREAD

**Issue by copyfun** [ToniJakovcevic/TensorFlow-Udacity#1]
``` python
    forget_gate = tf.sigmoid(res[:,num_nodes:2*num_nodes])
    input_gate = tf.sigmoid(res[:,:num_nodes])
    update_gate = tf.sigmoid(res[:,2*num_nodes:3*num_nodes])
    output_gate = tf.sigmoid(res[:,3*num_nodes:])
```

since assignment 6 problem 1 is just rewrite the matrix multiply, the perplexity should be similar.
original perplexity is 4.25 and yours is 6.25, so I looked into your code.
the update_gate calculation in original assignment code does not take a sigmoid.
I think you probably did that by mistake, and that maybe why perplexity is increasing.

**Comment by ToniJakovcevic** [comment]
Yes, I was wondering why the perplexity is higher than expected. You are right, the update_gate does not take a sigmoid. Now it works as expected. Thanks.
